name: fcb_calculator_v2_1
description: "FCB loan e mobile calculator."
publish_to: 'none'
version: 2.1.0+1
environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  jiffy: ^5.0.1
  intl: ^0.18.1
  fluttertoast: ^8.0.9
  flutter_cupertino_datetime_picker: ^3.0.0
  flutter_lints: ^1.0.4
  device_info_plus: ^3.2.4
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flow_builder: ^0.0.10
  equatable: ^2.0.5
  formz: ^0.6.1
  google_sign_in: ^6.2.1
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  firebase_database: ^10.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  firebase_auth_platform_interface: ^7.0.3
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/fcb-calculator.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/fcb-calculator.png
    - assets/splash.png
    - assets/profile-bg.png